 package lab5;

public class Questions {
//	WAP TO PRINT THE LENGTH OF A STRING
//  WAP TO CONVERT A STRING TO UPPERCASE
//	CONCATENATE TWO STRINGS AND PRINT THE RESULT
//	WAM THAT PRINTS "HELLO WORLD" CALLING IT FROM MAIN
//	WAM THAT ADDS TWO INTEGER ABD RETURNS SUM
//	WAM THAT TAKES A STRING AND PRINTS IT IN REVERSE ORDER WITHOUT USING BUILD IN REVERSE METHODS
}
